### ISSUE TITLE
Tools page need modification to match the Tools menu

### ISSUE THREAD

**Issue by sdash-github** [PeanutBase/jekyll-peanutbase#1]
Tools side bar and dropdown from main menu have now links pointing to appropriate locations. (Sven's work and already committed, 63bd235 ....)
The Tools page, http://dev.lis.ncgr.org:50053/tools/# still has unmodified links and need to be along the line of the menu and side bar.  The relevant file is tools/index.html.

**Comment by svengato** [comment]
The Tools page should update automatically, it did on my local Jekyll site after I modified _data/tools.yml (tools/index.html is a template and should not change). Do you need to rebuild the version at [http://dev.lis.ncgr.org:50053](http://dev.lis.ncgr.org:50053) ?

**Comment by sdash-github** [comment]
My local was already up to date. I didn't see the correct links in the tools page; they were of the form http://dev.lis.ncgr.org:50053/tools/#.  This was even after `sudo docker-compose up --build -d`.

I repeated it just now and the result is the same.
```
<$> git pull origin main
From https://github.com/PeanutBase/jekyll-peanutbase
 * branch            main       -> FETCH_HEAD
Already up to date.
```
Followed by
`<$> sudo docker-compose up --build -d`

**Comment by svengato** [comment]
Try
> sudo docker-compose up -d --build --no-deps

**Comment by sdash-github** [comment]
Nothing changed in tools page even after `sudo docker-compose up -d --build --no-deps`.

**Comment by svengato** [comment]
Maybe someone in the standup meeting can help.

**Comment by svengato** [comment]
Closing as this is more or less complete.
