### ISSUE TITLE
Announcement page

### ISSUE THREAD

**Issue by sdash-github** [PeanutBase/jekyll-peanutbase#16]
Sven can write the status here.

**Comment by svengato** [comment]
So far, there is only one Announcement, for PAG 30. Its page is pretty minimal, but contains a link to the PAG site which contains more information.

**Comment by svengato** [comment]
Why is there a second PAG 30 announcement? Otherwise we should be able to close this issue.

**Comment by sdash-github** [comment]
Explanation:  
I was trying to make the items in announcement to appear in order of their happening time rather than in the order in which they were listed. So, I changed the file names locally with new made up dates part in the file name. When committed & pushed resulted in duplicate post files.

-- I will delete the undesirable extra one after we sort out the issue, date in the file name vs. date inside the post in the date field.

Desirable: An improved announcement block 
(The current block is dependent on 'Posts' behavior which is different from listing events in a certain chronological order independent of when they were posted)
-- So that we have control over the order in which the items appear.
-- We should be able to insert an event in between existing event items (posts)
-- I need to understand the logic of how to determine listing order.

**Comment by sdash-github** [comment]
Now dependent on the outcome of the issue in LIS Jekyll site.
https://github.com/legumeinfo/jekyll-legumeinfo/issues/127#issue-1519494591

**Comment by svengato** [comment]
Announcements are now Events. @sdash-github, you may commit your recent Events any time.
