### ISSUE TITLE
Add a few variant datasets/tracks to JB2 manually

### ISSUE THREAD

**Issue by sdash-github** [PeanutBase/jekyll-peanutbase#20]
-- Add a few variant data:
Add manually the genotyping dataset tracks to JB2 config since Connor's script can't pick it up.

**Comment by adf-ncgr** [comment]
OK, I've added the three existing diversity sets for hypogaea:
- aradu1_araip1.gnm1.div.Clevenger_Korani_2018: Genotyping of African germplasm collection
- aradu1_araip1.gnm1.div.Otyama_Kulkarni_2020: Diversity data for the U.S. peanut core collection, genotyped relative to the diploid A. duranensis and A. ipaensis genome assemblies.
- aradu1_araip1.gnm1.div.Otyama_Wilkey_2019: Genotype data for US Peanut Mini Core collection.

to the jbrowse2 config for both the aradu.gnm1 and araip.gnm1 against which the variants in those files are located. As is typical, I also discovered that the compression for these genomes/annotations was not bgzip, so have fixed those. In case we ever need to recreate these following an autogenerate of the config by Connor's scripts, the commands I used to add these tracks to the configs are in my home dir on the dev-pb-jekyll VM: ~adf/jbrowse2_config_cmds
