### ISSUE TITLE
URL for PeanutBase Development site needed.

### ISSUE THREAD

**Issue by sdash-github** [PeanutBase/jekyll-peanutbase#21]
Currently the Peanutbase-Jekyll site URL is http://dev.lis.ncgr.org:50053/ and it needs a more appropriately named URL for sharing with collaborators and the outside world until we completely expose this server as the production site(peanutbase.org).
I am proposing plain and simple "**peanutbase-dev.org**".
**Need input from** @adf-ncgr and @cann0010 
Need to request Rex to formally after finalized.

**Comment by adf-ncgr** [comment]
Well, I think it would need to be dev.peanutbase.org or something else that ends with .peanutbase.org since this is the top-level domain that we control already (by we, I mean Rex). But otherwise, that's fine with me.

**Comment by sdash-github** [comment]
Email from Rex:
dev.peanutbase.org => dev.lis.ncgr.org
The dev-pb-jekyll VM and Fisher need to be modified at appropriate places  to reflect this.

**Comment by adf-ncgr** [comment]
OK try https://dev.peanutbase.org looks like it should be working now

**Comment by sdash-github** [comment]
Great. Thanks.
Sudhansu

**Comment by sdash-github** [comment]
Done.
