### ISSUE TITLE
The Peanut Genome page

### ISSUE THREAD

**Issue by svengato** [PeanutBase/jekyll-peanutbase#28]
The Peanut Genome
https://dev.peanutbase.org/genome

Changes between genome assemblies v1 and v2
https://dev.peanutbase.org/genome/peanut_genome_v1_v2

Issues:
- [ ] 1. Some links (IPGI, "Two diploid progenitors of cultivated peanut", GBrowse, JBrowse, data store assembly & annotation) still refer to the current peanutbase.org. Do we need to update these?
- [ ] 2. "IMPORTANT NOTE: the version 2.0 assembly (gnm2) for Arachis hypogaea var. Tifrunner has not been submitted to GenBank." Is this still true?
- [x] 3. Links to Aiden Lab and DNA Zoo Announcement are missing/obsolete, let me know if alternatives exist.
- [x] 4. Dot plots: should these go in the repository? (no, on falafel)

**Comment by svengato** [comment]
> Links to Aiden Lab and DNA Zoo Announcement are missing/obsolete, let me know if alternatives exist.

These are now fixed.

**Comment by sdash-github** [comment]
> Some links (IPGI, "Two diploid progenitors of cultivated peanut", GBrowse, JBrowse, data store assembly & annotation) still refer to the current peanutbase.org. Do we need to update these?

YES

> Dot plots: should these go in the repository?

We should keep them in falafel where PB files are stored and linked to. Only the page should go to pb-jekyll repo.

**Comment by svengato** [comment]
I moved the dot plots to falafel.

**Comment by svengato** [comment]
On the "Changes between v1 and v2" page, the **Downloads** links go to an old Legume Federation version of the data store. Should they go to the current LIS data store instead? And should we add the new gnm2.ann2 genome?

@sdash-github and @adf-ncgr : Should we link to the current data store, or leave it as is?

**Comment by svengato** [comment]
I made an IPGI (International Peanut Genome Initiative) page (under The Peanut Genome), but its content is pretty old and needs updating.

**Comment by svengato** [comment]
What is the correct format for phrases like "_Arachis hypogaea_ var. Tifrunner"? I think the botanical name should be in italics, and the cultivar name should have no highlighting? There is some inconsistency across pages.

**Comment by svengato** [comment]
Initial commit: c30b6c4. This includes **IPGI** and **Changes between genome assemblies v1 and v2** pages as well as the main page.

Known issues for main page (`genome/index.html`):
- [x] Fix various links (v1 and v2 assembly, annotation, GBrowse, JBrowse).
- [x] Fix link to "two diploid progenitors of cultivated peanut".
- [x] Fix links to PeanutBase datastore - should they link to the LIS datastore?
- [x] "IMPORTANT NOTE: the version 2.0 assembly (gnm2) for Arachis hypogaea var. Tifrunner has not been submitted to GenBank." Is this still true?

**Comment by sdash-github** [comment]
Genome page links rectified. To 'legacy.PB' and to correct DS link 'data.legumeinfo.org/Arachis' instead of 'PB/data/v2/etc.'  
Commit: 6171e33

**Comment by sdash-github** [comment]
The pb-jekyll-site/genome page is ready.  Any other refinement when needed will be done after transition. Closing issue.
