### ISSUE TITLE
NIFA PCCGP Project page

### ISSUE THREAD

**Issue by svengato** [PeanutBase/jekyll-peanutbase#29]
NIFA PCCGP Project
https://dev.peanutbase.org/germplasm/nifa_pccgp

Issue:
The Gigwa link is still under peanutbase.org. Are we planning to run Gigwa here? (The link would change to 'germplasm/gigwa' or something similar)

**Comment by sdash-github** [comment]
Need @adf-ncgr input to tell us a new url for gigwa2.5 and we then will use that url in pb-jekyll

From  pb-stage: http://localhost:9000/germplasm/gigwa.
<iframe id="frameviewer" frameborder="0" width="1200" height="1500" scrolling="yes"  src="https://peanutbase.org/gigwa/"   name="frameviewer">

**Comment by sdash-github** [comment]
Already in VM that hosts pb-jekyll.
@adf to create a proxy to point to dev.pb-jekyll.

Independent page like JB2.

**Comment by adf-ncgr** [comment]
I forgot that I had already set this up as:
https://dev.peanutbase.org/gigwa/

I would prefer to be consistent with other tools and have it as https://dev.peanutbase.org/tools/gigwa/ but there appears to be a problem with having it sit at anywhere besides /gigwa for now. Maybe not an insurmountable problem, but I will need to spend some time with the gigwa config options to see if they enable this.

**Comment by svengato** [comment]
I pointed all Gigwa links to `/gigwa`.

**Comment by svengato** [comment]
This page seems ready to commit.

@sdash-github To check for readiness.

**Comment by svengato** [comment]
Added in commit 85da876.
