### ISSUE TITLE
Contact Page or Card or Link: Need one

### ISSUE THREAD

**Issue by sdash-github** [PeanutBase/jekyll-peanutbase#3]
-- Like the one we have at https://peanutbase.org/contact with Captcha.
-- Ideally a link in header such that if our user clicks it the form is aware of and retains the URL of the page. where it was clicked. The email to us will include this URL and this is useful info when we investigate the issue or frame a response.

**Comment by svengato** [comment]
The personnel sections at the bottom are easy, I modified contact/index.html so that if you add people to _data/personnel.yml it updates automatically.

The Contact form is trickier. There are some services that let you paste a form template into a static site, including
  [FormKeep](https://formkeep.com)
  [FormSpree](https://formspree.io)
  [Getform](https://getform.com)
In each case, you have to sign up for an account. I am researching whether their forms retain the source URL.

**Comment by svengato** [comment]
> I modified contact/index.html so that if you add people to _data/contact.yml it updates automatically.

Really _data/personnel.yml.

**Comment by svengato** [comment]
Using [Formspark](https://formspark.io/), tested that it works (without the captcha yet, that requires HTTPS). But I see that the free tier is not 250 submissions/month but 250 total, so we may want to change to another service.

**Comment by svengato** [comment]
Added the Contact form and its personnel data. It works as expected (in separate tests), but full functionality is not yet enabled in the repository version. For now, clicking the Send Message button shows a JSON page with the data that would have been submitted.

**Comment by svengato** [comment]
Enabled for production, but disabled on dev-peanutbase (use "echo" instead of the Formspark action id, and comment out the recaptcha).

**Comment by svengato** [comment]
Is this issue ready to close? We just need to note when (if ever) the number of Contact form messages approaches the Formspark limit.

**Comment by sdash-github** [comment]
Test-A.
Contact clicked from home page from my local docker instance (localhost:4000/).
Email received with correct referer page url.

Test-B
=====
Cliclked from https://dev.peanutbase.org/tools/sequenceserver.
Referer is blank in email. Likely from 'but disabled on dev-peanutbase' (https://github.com/PeanutBase/jekyll-peanutbase/issues/3#issuecomment-1295203565)

So, yes can close issue and reopen if necessary when site is active as production.

**Comment by sdash-github** [comment]
Closing as nothing to do for now.
