### ISSUE TITLE
Germplasm Seed Images page

### ISSUE THREAD

**Issue by svengato** [PeanutBase/jekyll-peanutbase#30]
Links point to peanutbase.org, we should move them to dev.peanutbase.org

**Comment by svengato** [comment]
I built a template and data set for the germplasm images, but a lot of them are missing from the `brilliant_gallery_temp` directory, for example `bg_cached_resized_f917beaaad5b71a86452a05efb35bd18.jpg`. Maybe the image file backup only partially completed?

This applies to pod  (#31) and plant (#32) images as well.

**Comment by svengato** [comment]
There should be 3862 images (1931 each small and large versions), but there are only 1208. Next: write a script to collect the missing ones. A few may not be possible as their URL on the PeanutBase site is under localhost.

**Comment by svengato** [comment]
Added a JavaScript Lightbox implementation, which should display and highlight the large version of each image when you click on the small image. But right now it looks like the large images are among the missing ones.

**Comment by svengato** [comment]
I found 1721 of the missing images and copied them to falafel (`peanutbase/files-from-legacy/drupal7-site-default-files/missing-germplasm-images`, and then `peanutbase/files/brilliant_gallery_temp`). Now 2929 of 3862 germplasm images are available.

I also added the accession name underneath each image so users can search for them.

**Comment by sdash-github** [comment]
#### Summary after 2023/0420 meeting Sven & Sudhansu:  
* BrilliantGallery/ contains original files from source and Drupal BrilliantGallery library (bg-lib)  
* The brilliant_gallery_temp/ dir contains thumbnail files generated by the bg-lib.  This is an incomplete collection as they were created on the fly by bg-lib as needed.  
* We decided Sven would have a **quick but temp** work around this using the thumbnail images from brilliant_gallery_temp/ dir; but,
*  The **permanent solution** would be to generate the thumbnail images ourselves and use those in  pb-jekyll along with the original 1931 images. 

TO DO: @sdash-github to generate the entire 1931 thumbnail images from the original Noelle Barkley collection.

**Comment by svengato** [comment]
All images now live under `files/`. Pages generated automatically since commit 4abdbe5.
