### ISSUE TITLE
Germplasm Catalogs page

### ISSUE THREAD

**Issue by svengato** [PeanutBase/jekyll-peanutbase#33]
This page already existed, I did some minor cleanup.

**Comment by svengato** [comment]
After a bit more cleanup, I think it is ready to commit.

**Comment by sdash-github** [comment]
SD to Check if ready

**Comment by sdash-github** [comment]
Looks good. 
@svengato can close after commit.

**Comment by svengato** [comment]
See commit 65a69eb.
