### ISSUE TITLE
Generate thumbnail germplasm images from Noelle Barkley original collection

### ISSUE THREAD

**Issue by sdash-github** [PeanutBase/jekyll-peanutbase#34]
@sdash-github to generate thumbnail germplasm images from Noelle Barkley original collection which were used in Drupal Brilliant Gallery library. Based on issue:     
https://github.com/PeanutBase/jekyll-peanutbase/issues/30#issuecomment-1523981043   

Use ImageMagick and a script to create thumbnails for the entire dir tree and put it in /falafel/peanutbase location side by side with original image dir for use by @svengato.

**Comment by sdash-github** [comment]
### WORK:
* Work done in [sdash@mbp02 ~/sdmilam/projects/brillGalleryThGenerate].  
* /falafel/peanutbase/files-from-legacy/drupal7-site-default-files/BrilliantGallery  copied from falafel to local.
* Overall plan: used find -type f (lists files with path); then exec mogrify (imagemagick) to convert to thumbnails and put them in a thumbnails dir.
* Notes in [sdash@mbp02 ~/sdmilam/projects/brillGalleryThGenerate/notes.
* Script:  run-mogrify-on-brillGal-dir.bash* in local dir

### RESULT:
* Original files location:  /falafel/peanutbase/files-from-legacy/drupal7-site-default-files/BrilliantGallery/.......
*  **Thumbnail files location:**  /falafel/peanutbase/files/BrilliantGalleryThumbnails/.......(****Note the files/ dir location as opposed to original dirs copied from Drupal site**)
* Exact same dir structure  as original but filenames with .gif extension.
* Thumbnail files are gif files as opposed to jpg originals to distinguish them from original and are supposed to be better for webpages comapared to jpg.
*  Total 1931 thumbnail files as in original.
* Three files have modified filenames to remove 'parenthesis' in oroginal filenames per below.
 "PI497631_(2)_FINAL_RESIZED.jpg"  PI497631_2_FINAL_RESIZED.jpg
 "PI502045_xtra3_(2)_FINAL_RESIZED.jpg"  PI502045_xtra3_2_FINAL_RESIZED.jpg
 "pi476063_(2)_FINAL_RESIZED.jpg"  pi476063_2_FINAL_RESIZED.jpg  

### TO DO:  @svengato  to close issue after his needs are met .

**Comment by svengato** [comment]
Working on this today, there are some title v. filename discrepancies so it will take a while to clean up.

**Comment by sdash-github** [comment]
Hi Sven,
I am on leave today because of a family commitment. I will not be checking
emails until after late afternoon.  Just wanted to let you know.
Sudhansu

**Comment by svengato** [comment]
@sdash-github: when you get back, could you restart the Jekyll site's Docker container? It does not build for me any more (possibly due to a disconnection while trying to rebuild it).

**Comment by svengato** [comment]
Never mind, I got it back up. Still working on correcting filenames and directory structure, but most thumbnails should now appear.

**Comment by sdash-github** [comment]
Thanks Sven.
I tried yesterday: docker down, docker up, etc. Nothing worked, only 
ended up shwing the error message that a long hex string as image name 
is not active or something like that. I didn't try anything beyond that 
thought yesterday.  I am glad you solved it. Just curious as to what 
happened and how you solved it.
All is well that end well.

Sudhansu

**Comment by svengato** [comment]
I had made another symbolic link, to the full size images in `files-from-legacy/drupal7-site-default-files/BrilliantGallery/`, but had not added this to the Docker configuration. The right way is to copy those images to somewhere in `files/`, which is my next task.

**Comment by svengato** [comment]
That works. Next: clean up title (accession) v. filename discrepancies.

**Comment by svengato** [comment]
> Three files have modified filenames to remove 'parenthesis' in oroginal filenames per below.
> "PI497631_(2)FINAL_RESIZED.jpg" PI497631_2_FINAL_RESIZED.jpg
> "PI502045_xtra3(2)FINAL_RESIZED.jpg" PI502045_xtra3_2_FINAL_RESIZED.jpg
> "pi476063(2)_FINAL_RESIZED.jpg" pi476063_2_FINAL_RESIZED.jpg

I think you mean the thumbnail .gif files? The `(2)` should be present, for consistency with the title (accession). I changed these .gif filenames to include it, also a few others with extensions like `.JPG` instead of `.jpg`, or with a misspelled directory name like `Attalpulgus`.

All 1931 thumbnail files are visible now, but I have not checked all of the large images.

**Comment by sdash-github** [comment]
Checked the seed, pods, plants, etc. categories of images at random and a few from each category: The larger images are displayed okay.

Can close the issue if @svengato okays it.

**Comment by svengato** [comment]
The large images are in `files/BrilliantGallery/NoelleBarkley/...`, and the thumbnails are in `files/BrilliantGalleryThumbnails/NoelleBarkley/...`.

**Comment by sdash-github** [comment]
### Dropping Brilliant Gallery from dir names??
Would it be a big issue to remove the "BrilliantGallery" from the dir names?
-- It was just the Drupal library name we used and is now history and not relevant anymore.
-- We should retain NoelleBarkley label because it is her collection of images that she shared with me. Although she is "Noelle Anglin" now. It will be nice to have a resolution of this name related issue although we don't have to, at least right away. Any good idea that is culturally sound?

**Comment by svengato** [comment]
> Would it be a big issue to remove the "BrilliantGallery" from the dir names?

No, that would be easy. How about `Noelle/Thumbnails` and `Noelle/Images`? (see below)

> Any good idea that is culturally sound?

Just "Noelle"? Or you could ask what she prefers.

**Comment by sdash-github** [comment]
I am fine with Noelle and the webpage would have full name of the 
contributor of this resource, Noelle Anglin (previously Barkley).

**Comment by svengato** [comment]
The pages that mention her already use "Noelle Anglin" or "Noelle L. Anglin", except for the **Contributor** and **Photographer** tags in the germplasm images pages, which use "Noelle Barkley". Should I change those to "Noelle Anglin"?

**Comment by sdash-github** [comment]
I would let that stay as it is.

**Comment by svengato** [comment]
Done - no further references to `BrilliantGallery`.
