### ISSUE TITLE
Gene keyword search enhancements

### ISSUE THREAD

**Issue by svengato** [PeanutBase/jekyll-peanutbase#36]
Recent enhancements to the gene keyword search web component include:
- Can filter by genus, species, strain
- Can specify keyword search for gene identifier, description, or gene family id
- Displays results in a list instead of a table.
- Results contain more information than just gene name and description: full gene identifier, genus + species + strain, location, gene family.

I have rebuilt the PeanutBase Jekyll site on another computer, and am ready to do it on dev-pb-jekyll.
1. Is everyone okay with the list format? Should we do the same for trait keyword search?
2. The previous search result returned an id from which we could create a link directly to a report page in ArachisMine, but the new results do not. (This applied to gene name, and now also to gene family.) I suggest that we link to an ArachisMine keyword search page instead, then the user can select the desired report page.

**Comment by sdash-github** [comment]
Is it possible to have a look at it?

**Comment by svengato** [comment]
Current results look like

<img width="1231" alt="gene-search-old" src="https://github.com/PeanutBase/jekyll-peanutbase/assets/8918336/25330d05-8bdf-4b88-9b2c-0b4fc3c93acb">

New results look like

![gene-search-new](https://github.com/PeanutBase/jekyll-peanutbase/assets/8918336/ef47f318-0860-4b21-b408-bf83499ab308)

**Comment by sdash-github** [comment]
New one is certainly better.
List vs table.
1. (List) Should have total no of results and if paginated, the numbers 
in view.
2. Is it possible to download the entire result set? (in this case a 
table format is useful)
3. For comparison, say by location, a tabular view has an advantage.
4. Since there are only four cols (id, description, location, gene 
family) table view can be made not to go beyond screen width and won't 
hide info without horizontal scrolling.

I am leaning for table view. Please @svengato and @adf-ncgr weigh in.

**Comment by svengato** [comment]
> 2. The previous search result returned an id from which we could create a link directly to a report page in ArachisMine, but the new results do not. (This applied to gene name, and now also to gene family.) I suggest that we link to an ArachisMine keyword search page instead, then the user can select the desired report page.

I figured out how to link directly to the report page, so we may as well keep that as it is.

**Comment by svengato** [comment]
I agree about total number of results and currently displayed results, it looks like now we are only showing the number of results currently displayed (not the total).

One advantage of the list format is less wasted space for rows where gene description is long and other fields are short (the description should not be compressed into a narrow table cell).

**Comment by svengato** [comment]
We decided that pagination is a low priority for now.

**Comment by svengato** [comment]
Updated in commit ee6e5eb3a24d7ac26b032b7c2e2c7a5c0fb929b6, then added gene family links to ArachisMine in commit 29d771a48595ac89c209d673e8af6939d13ce2be.
