### ISSUE TITLE
SSL certificate for dev site

### ISSUE THREAD

**Issue by sdash-github** [PeanutBase/jekyll-peanutbase#43]
I am having problem opening site dev.peanutbase.org, but, https://dev.pb.lis.ncgr.org/ opens okay.  
Privacy error: "NET::ERR_CERT_COMMON_NAME_INVALID"

It is related to another issue where I am constructing a url to show plantuml infographics of steps for JB2 use.
Here I am testing a hardcoded url because I haven't figured out the complex plantuml url construction in liquid template. This will be another issue.

**Comment by sdash-github** [comment]
Relates to issue #44

**Comment by adf-ncgr** [comment]
OK, it should be working for https://dev.peanutbase.org/ now, but probably no longer for  https://dev.pb.lis.ncgr.org/ 
Unless there's a reason we want to retain the latter, I will just remove it from DNS

**Comment by adf-ncgr** [comment]
closing, feel free to reopen if issues persist
