### ISSUE TITLE
Google Analytics in PB-Jekyll site

### ISSUE THREAD

**Issue by sdash-github** [PeanutBase/jekyll-peanutbase#48]
In **dev-pb-jekyll**.
_config.yml now has  the line 'google_analytics: "UA-49655154-2"'.
Even after Sven got the theme updated and I have rebuild the site after deleting the _site/ dir, I don't find the typical commented line for this and  the sctipt tags under it.
```<!-- Global site tag (gtag.js) - Google Analytics -->``` as found now in LIS site.

**Comment by sdash-github** [comment]
Problem (Alan found):
The _config.yml line should be google_analytics_id: ".....". Was google_analytics: "".
Corrected and works in dev.
PROD: Changed but it doesn't show the needed line in page source. May be theme hasn't been updated. Ask @svengato

**Comment by svengato** [comment]
After changing the jekyll-theme-legumeinfo branch to `main` and rebuilding the Jekyll site, now https://www.peanutbase.org shows the Google Analytics line. Do we need anything from the `taxon-autocontent` branch?

**Comment by adf-ncgr** [comment]
yes there are some diffs
https://github.com/legumeinfo/jekyll-theme-legumeinfo/compare/main...taxon-autocontent#diff-14172c7f366f3dfdded56c24b6bf8e157c7401498c5bc7beac246c89c6edfaaa
that make the page https://www.peanutbase.org/taxa/arachis/ have content that it looks to now be missing. I can try to get the ASAP referred to in https://github.com/legumeinfo/jekyll-theme-legumeinfo/pull/22#issuecomment-1728387821 to happen so we can get it all merged into main

**Comment by adf-ncgr** [comment]
FYI, I've flipped the production version back to using taxon-autocontent branch until we merge it (which I anticipate will happen tomorrow after @alancleary resolves my confusion over how many example _data dirs are actually needed); figured having page content was more important for than invisible google spies.

**Comment by sdash-github** [comment]
I see production-pb has the "Global site tag (gtag.js) - Google Analytics" in place now. It wasn't after adf's reversal.

**Comment by adf-ncgr** [comment]
sorry I meant to mention that I took it back to main after merging in the taxon-autocontent branch, so all should be good now.   Closing
